name = "Scizzorz"
license = "MIT"
licenselink = "https://github.com/scizzorz/scizzorz-hugo/blob/master/LICENSE"
description = "Hugo for Scizzorz?"
homepage = "https://github.com/scizzorz/scizzorz-hugo/"
tags = []
features = ["blog"]
min_version = "0.20"

[author]
  name = "Scizzorz"
  homepage = "scizzorz.com"
